"""
src/ui/export.py
----------------
Export helpers: CSV, Markdown report, and JSON summary builders.

All exported content includes a mandatory scientific limitation notice.
Fields marked as demo/fallback are clearly labeled in every export format.

Owned by: M4 (Frontend/UI Lead)
"""
from __future__ import annotations

import json
from datetime import datetime
from io import StringIO

import pandas as pd

from src.ui.schema import FrontendCandidate

_DISCLAIMER = """
---
## Scientific Limitation

TargetForge outputs are computational hypotheses generated under a hackathon
demonstration context. Activity scores are deterministic hash-based demo values,
not real machine-learning predictions. Docking scores are fallback estimates,
not real AutoDock Vina / Glide / DOCK outputs. Novelty scores are hardcoded demo
constants (0.5 for all candidates). This report does not establish safety, efficacy,
clinical benefit, or regulatory approval of any molecule. Laboratory validation is
required before drawing any scientific conclusions.

Generated by TargetForge (hackathon prototype).
"""

_TIMESTAMP = lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S")


# ---------------------------------------------------------------------------
# CSV exports
# ---------------------------------------------------------------------------

def build_ranking_csv(candidates: list[FrontendCandidate]) -> str:
    """Flat CSV of the FrontendCandidate ranking list."""
    if not candidates:
        return "No candidates to export."
    rows = []
    for c in candidates:
        rows.append({
            "rank":              c.rank,
            "compound_id":       c.candidate_id,
            "smiles":            c.smiles,
            "source":            c.source,
            "activity_score":    c.activity_score,
            "activity_score_note": "deterministic_demo" if c.is_demo else "real",
            "predicted_class":   c.predicted_class,
            "model_version":     c.model_version,
            "mw":                c.properties.mw,
            "logp":              c.properties.logp,
            "hbd":               c.properties.hbd,
            "hba":               c.properties.hba,
            "tpsa":              c.properties.tpsa,
            "rotatable_bonds":   c.properties.rotatable_bonds,
            "property_score":    c.property_score,
            "filter_status":     c.filter.status,
            "filter_reasons":    "; ".join(c.filter.reasons),
            "docking_score_raw": c.docking.score_raw,
            "docking_score_note": "FALLBACK_DEMO" if c.is_demo else "real",
            "docking_score_normalized": c.docking.score_normalized,
            "receptor_id":       c.docking.receptor_id,
            "docking_status":    c.docking.docking_status,
            "novelty_score":     c.novelty_score,
            "novelty_score_note": "hardcoded_0.5_demo" if c.is_demo else "real",
            "final_score":       c.final_score,
            "status":            c.status,
            "is_demo":           c.is_demo,
        })
    buf = StringIO()
    pd.DataFrame(rows).to_csv(buf, index=False)
    return buf.getvalue()


def build_validated_csv(validated_df: pd.DataFrame | None) -> str:
    """CSV of the validated molecules DataFrame."""
    if validated_df is None or validated_df.empty:
        return "No validated molecules to export."
    buf = StringIO()
    validated_df.to_csv(buf, index=False)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

def build_markdown_report(state: dict, sections: list[str] | None = None) -> str:
    """
    Full Markdown report from session state snapshot.

    Parameters
    ----------
    state    : a dict-like copy of st.session_state keys.
    sections : list of section keys to include. If None, all are included.
               Keys: "target", "dataset", "screening", "filter",
                     "docking", "ranking", "disclaimer"
               "disclaimer" is always included regardless of sections list.
    """
    include_all = sections is None
    def _inc(key: str) -> bool:
        return include_all or key in (sections or [])

    lines: list[str] = []
    ts = _TIMESTAMP()

    lines.append(f"# TargetForge Screening Report")
    lines.append(f"\n*Generated: {ts}*\n")

    # Target Summary
    if _inc("target"):
        target = state.get("tf_target") or {}
        lines.append("## Target Summary\n")
        lines.append(f"| Field | Value |")
        lines.append(f"|---|---|")
        lines.append(f"| Disease | {target.get('disease', 'N/A')} |")
        lines.append(f"| Target | {target.get('name', 'N/A')} |")
        lines.append(f"| Aliases | {', '.join(target.get('aliases', []))} |")
        lines.append(f"| PDB Structure | {target.get('structure_id', 'N/A')} |")
        lines.append(f"| Model | {target.get('model_version', 'N/A')} (demo) |")
        lines.append("")

    # Dataset Statistics
    if _inc("dataset"):
        valid_df    = state.get("tf_validated_df")
        rejected_df = state.get("tf_rejected_df")
        n_valid    = len(valid_df)    if valid_df    is not None else 0
        n_rejected = len(rejected_df) if rejected_df is not None else 0
        lines.append("## Dataset Statistics\n")
        lines.append(f"| Metric | Count |")
        lines.append(f"|---|---|")
        lines.append(f"| Valid compounds | {n_valid} |")
        lines.append(f"| Rejected compounds | {n_rejected} |")
        lines.append(f"| Total loaded | {n_valid + n_rejected} |")
        lines.append("")

    # AI Screening Summary
    if _inc("screening"):
        model_meta = state.get("tf_model_meta") or {}
        lines.append("## AI Screening Summary\n")
        lines.append(f"> ⚠ Activity scores are deterministic demo values (SHA-256 hash). Not real ML predictions.\n")
        lines.append(f"| Field | Value |")
        lines.append(f"|---|---|")
        lines.append(f"| Model version | {model_meta.get('model_version', 'demo_v1')} |")
        lines.append(f"| Model type | {model_meta.get('model_type', 'demo_activity_model')} |")
        lines.append("")

    # Filter Results
    if _inc("filter"):
        filter_cfg = state.get("tf_filter_config") or {}
        filtered_df = state.get("tf_filtered_df")
        n_pass = len(filtered_df[filtered_df.get("filter_status", pd.Series()) == "PASS"]) \
            if filtered_df is not None and "filter_status" in filtered_df.columns else "N/A"
        lines.append("## Filter Results\n")
        lines.append(f"| Property | Threshold |")
        lines.append(f"|---|---|")
        lines.append(f"| MW | ≤ {filter_cfg.get('max_molecular_weight', 500)} Da |")
        lines.append(f"| LogP | ≤ {filter_cfg.get('max_logp', 5.0)} |")
        lines.append(f"| HBD | ≤ {filter_cfg.get('max_hbd', 5)} |")
        lines.append(f"| HBA | ≤ {filter_cfg.get('max_hba', 10)} |")
        lines.append(f"| TPSA | ≤ {filter_cfg.get('max_tpsa', 140)} Å² |")
        lines.append(f"\nCompounds passing all filters: **{n_pass}**\n")
        lines.append("")

    # Docking Results
    if _inc("docking"):
        lines.append("## Docking Results\n")
        lines.append("> ⚠ **FALLBACK_DEMO** — All docking scores are deterministic estimates computed from compound identifiers. No real molecular docking simulation was performed.\n")
        candidates: list[FrontendCandidate] = state.get("tf_candidates") or []
        if candidates:
            lines.append("| Rank | Compound | Docking Score (kcal/mol) | Status |")
            lines.append("|---|---|---|---|")
            for c in candidates:
                ds = f"{c.docking.score_raw:.3f}" if c.docking.score_raw is not None else "N/A"
                lines.append(f"| {c.rank} | {c.candidate_id} | {ds} | {c.docking.docking_status} |")
        lines.append("")

    # Final Ranking
    if _inc("ranking"):
        weights    = state.get("tf_weights") or {}
        candidates = state.get("tf_candidates") or []
        lines.append("## Final Candidate Ranking\n")
        lines.append(f"Weights — Activity: {weights.get('activity_weight',0.4):.0%} | "
                     f"Docking: {weights.get('docking_weight',0.3):.0%} | "
                     f"Property: {weights.get('property_weight',0.2):.0%} | "
                     f"Novelty: {weights.get('novelty_weight',0.1):.0%}\n")
        if candidates:
            lines.append("| Rank | Compound | Activity ⚠DEMO | Docking ⚠DEMO | Property | Novelty ⚠DEMO | Final Score | Status |")
            lines.append("|---|---|---|---|---|---|---|---|")
            for c in candidates:
                ds = f"{c.docking.score_raw:.3f}" if c.docking.score_raw is not None else "N/A"
                lines.append(
                    f"| {c.rank} | {c.candidate_id} | {c.activity_score:.4f} | "
                    f"{ds} | {c.property_score:.1f} | "
                    f"{c.novelty_score:.2f} | {c.final_score:.4f} | {c.status} |"
                )
        lines.append("")

    # Scientific Disclaimer (always included)
    lines.append(_DISCLAIMER)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# JSON summary
# ---------------------------------------------------------------------------

def build_summary_json(state: dict) -> str:
    """Structured JSON of session metadata and candidate list."""
    target    = state.get("tf_target")      or {}
    weights   = state.get("tf_weights")     or {}
    filter_cfg = state.get("tf_filter_config") or {}
    candidates = state.get("tf_candidates") or []

    payload = {
        "report_generated_at": _TIMESTAMP(),
        "is_demo_mode":        state.get("tf_demo_mode", True),
        "scientific_note":     (
            "All scores are computational estimates from a hackathon demo. "
            "Not validated scientific results."
        ),
        "target": {
            "name":         target.get("name"),
            "aliases":      target.get("aliases"),
            "structure_id": target.get("structure_id"),
            "disease":      target.get("disease"),
        },
        "model": {
            "version": target.get("model_version"),
            "type":    target.get("model_type"),
        },
        "ranking_weights":   weights,
        "filter_thresholds": filter_cfg,
        "candidates": [
            {
                "rank":            c.rank,
                "candidate_id":    c.candidate_id,
                "smiles":          c.smiles,
                "activity_score":  c.activity_score,
                "activity_note":   "deterministic_demo" if c.is_demo else "real",
                "docking_score":   c.docking.score_raw,
                "docking_note":    "FALLBACK_DEMO"      if c.is_demo else "real",
                "property_score":  c.property_score,
                "novelty_score":   c.novelty_score,
                "novelty_note":    "hardcoded_0.5_demo" if c.is_demo else "real",
                "final_score":     c.final_score,
                "filter_status":   c.filter.status,
                "filter_reasons":  c.filter.reasons,
                "properties": {
                    "mw":              c.properties.mw,
                    "logp":            c.properties.logp,
                    "hbd":             c.properties.hbd,
                    "hba":             c.properties.hba,
                    "tpsa":            c.properties.tpsa,
                    "rotatable_bonds": c.properties.rotatable_bonds,
                },
                "is_demo": c.is_demo,
            }
            for c in candidates
        ],
    }
    return json.dumps(payload, indent=2, default=str)
