"""
src/ui/schema.py
----------------
Frontend data-layer schemas for TargetForge.

FrontendCandidate and its sub-dataclasses represent the normalised view
the UI uses for display, filtering, and what-if ranking.  They are
NEVER written back to any backend module.

Owned by: M4 (Frontend/UI Lead)
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Sub-structures
# ---------------------------------------------------------------------------

@dataclass
class MolecularProperties:
    """Lipinski / ADMET descriptors for a candidate molecule."""
    mw: float = 0.0
    logp: float = 0.0
    hbd: int = 0
    hba: int = 0
    tpsa: float = 0.0
    rotatable_bonds: int = 0


@dataclass
class FilterResult:
    """Property-filter outcome for a candidate molecule."""
    status: str = "UNKNOWN"        # "PASS" | "REJECTED" | "UNKNOWN"
    reasons: list[str] = field(default_factory=list)
    # e.g. ["MW 520.1 > 500", "LogP 5.3 > 5.0"]


@dataclass
class DockingResult:
    """Docking simulation result for a candidate molecule."""
    score_raw: Optional[float] = None        # kcal/mol from backend
    score_normalized: Optional[float] = None # 0–1, 1=best; from backend docking_norm
    pose_file: Optional[str] = None          # path/file; None in demo mode
    receptor_id: Optional[str] = None        # e.g. "6LU7"
    interaction_residues: list[str] = field(default_factory=list)
    docking_status: str = "UNKNOWN"          # "FALLBACK_DEMO" | "REAL" | "UNKNOWN"


# ---------------------------------------------------------------------------
# Primary frontend candidate record
# ---------------------------------------------------------------------------

@dataclass
class FrontendCandidate:
    """
    Normalised candidate record used throughout the TargetForge UI.

    Fields marked 'BACKEND — read-only' are mapped directly from the
    pipeline DataFrame and must never be recalculated or overwritten
    by UI code.

    Fields marked 'UI-only' are generated by the adapter/UI layer and
    are not present in the backend DataFrame.
    """

    # --- Identity ---
    candidate_id: str = ""
    smiles: str = ""
    source: str = "demo"           # "demo" | "upload" | "generated"
    parent_id: Optional[str] = None   # for designed analogues (future)

    # --- ML prediction (BACKEND — read-only) ---
    activity_score: float = 0.0
    model_version: str = "unknown"
    predicted_class: str = "unknown"  # "active" | "lower_priority"

    # --- Molecular properties (BACKEND — read-only) ---
    properties: MolecularProperties = field(default_factory=MolecularProperties)

    # --- Filter result (BACKEND + UI-derived reasons) ---
    property_score: float = 0.0        # BACKEND — read-only
    filter: FilterResult = field(default_factory=FilterResult)

    # --- Docking result (BACKEND — read-only) ---
    docking: DockingResult = field(default_factory=DockingResult)

    # --- Scoring (BACKEND — read-only) ---
    novelty_score: float = 0.5         # currently hardcoded 0.5 by backend
    final_score: float = 0.0           # BACKEND — NEVER recalculated by UI
    rank: int = 0                      # BACKEND — NEVER recalculated by UI
    status: str = "priority computational candidate"

    # --- Normalised components (BACKEND — used for what-if only) ---
    activity_norm: float = 0.0         # from backend activity_norm column
    docking_norm: float = 0.0          # from backend docking_norm column

    # --- What-if analysis (UI-only — stored separately, not official) ---
    whatif_score: Optional[float] = None
    whatif_rank: Optional[int] = None

    # --- UI metadata (UI-only) ---
    is_demo: bool = True
    warnings: list[str] = field(default_factory=list)
    # e.g. ["activity_score: deterministic demo value (SHA-256 hash)"]
